# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bloscCompressImpl <- function(data, level, filter = "blosclz") {
    .Call(`_Rblosc_bloscCompressImpl`, data, level, filter)
}

bloscDecompressImpl <- function(data, original_size) {
    .Call(`_Rblosc_bloscDecompressImpl`, data, original_size)
}

